Dev intake
RoboLancers/321-Crescendo-2024 pull request #6
Opened 2024-01-24 20:11 UTC by Floofyer

Added the basic functions for intake.

2024-01-24 22:29 UTC, Gitter499 requested changes

2024-01-24 22:29 UTC, Gitter499 commented on Intake.java
> +  public CANSparkMax intakemotor;
use camel case
e.g. intakeMotor

2024-01-24 22:29 UTC, Gitter499 commented on Intake.java
> +  public void intake() {
Constructor should always be upper case (same with the class)

Please run ./gradlew spotlessApply

2024-01-24 22:29 UTC, Gitter499 commented on Intake.java
Lmao remove this pls

2024-01-24 22:29 UTC, Gitter499 commented on src/main/java/org/robolancers321/subsystem/Intake.java
> +  public void intake() {
bug, constructor name should match class name and should always be capital

2024-01-24 22:29 UTC, Gitter499 commented on src/main/java/org/robolancers321/subsystem/Intake.java
> +  public int kport = 0;
use camel case

kPort

2024-01-24 22:29 UTC, Gitter499 commented on src/main/java/org/robolancers321/subsystem/Intake.java
> +  public CANSparkMax intakemotor;
use camel case

intakeMotor

2024-01-24 22:29 UTC, Gitter499 commented on src/main/java/org/robolancers321/subsystem/Intake.java
Where is the PID controller used?

2024-01-29 15:31 UTC, mattperls-code commented
closing this PR to merge both intake subsystems into their own branch for testing before dev

2024-01-29 15:31 UTC, closed without merging